### ISSUE TITLE
Timezone environment doesn't work in docker

### ISSUE THREAD

**Issue by uebmaster** [LibreBooking/docker#11]
I've changed the TZ value in docker-compose.yml and the timezone is not reflected in librebooking.

Compose file:

![image](https://user-images.githubusercontent.com/5565506/233163102-f9a53b98-2005-4f28-98cc-41a008bdcf73.png)

After run docker compose, Application Configuration show America/New_York.

Then i change it to America/Mexico_City, but when i go to Server Settings it shows this:

![image](https://user-images.githubusercontent.com/5565506/233163658-00abba02-e210-46ea-a64c-9d5055e4535e.png)

That is not the real time.

How can i change it to America/Mexico_City?

Thanks in advance.

**Comment by ben13300** [comment]
Dear @uebmaster , i think you will be able to change the timezone inside your config.phpµ
![image](https://user-images.githubusercontent.com/43414622/233207992-6f32e3a5-903e-4d8a-bc55-ec54779e06f7.png)
![image](https://user-images.githubusercontent.com/43414622/233208095-e40354b2-7207-47aa-9504-2928d812001d.png)

**Comment by uebmaster** [comment]
@ben13300 that was the first that i tried, but doesn't works.

**Comment by colisee** [comment]
Hola @uebmaster 

First of all, thank you for your pull request regarding the wrong URL in the Dockerfile, as I forgot to update it since the main project was moved to the new librebooking namespace in github. I took the liberty to drop the commented wrong/old line.

Regarding the timezone issue, could you please run the following commands when performing the test? 
```
docker volume rm librebooking_html librebooking-db_data
docker-compose up --detach
docker exec --tty librebooking-db sh -c 'date'
docker exec --tty librebooking sh -c 'date'
```

I believe it should work, thanks to the script entrypoint.sh. 
But then I realize that this script could have changed the timezone setting inside librebooking. I will make the change and push the new images to the docker's hub.

Saludos.

**Comment by uebmaster** [comment]
@colisee really i think that was my first pull request xD the true is that i'm not a developer, in fact, that was the reason for comment the original line cause i was not sure what i was suggesting were correct lol.

Regarding the timezone issue, I've already tested verifying the date in both containers and host, and all showed the right date, if i modified the date in librebooking's setup application i was able to change it, but when i check in server settings the time still being UTC +00:00, i don't know if this is right, but i have some standalone (bare metal) installs of bookedscheduler (when was free) and librebooking and it shows the right date and hour.

I wouldn't have a problem if it was only aesthetic, but since there was a time change in Mexico, in the other installs they couldn't create reservations due to the configured rules.

I suppose that is something relationated with librebooking, cause the date in containers shows correctly.

What could be?

Thanks in advance.

**Comment by uebmaster** [comment]
@colisee 

when run

`docker exec librebooking sh -c "php -i | grep 'date.timezone'"`

i get

`date.timezone => no value => no value`

this could be the cause?

**Comment by uebmaster** [comment]
@colisee yeah, is that the cause, the timezone in apache is not configured in the container, i had to copy /usr/local/etc/php/php.ini-development to /usr/local/etc/php/php.ini, 

then uncomment the 

`;date.time = `
(the value was empty)

and add the timezone `America/Mexico_City`

Restart apache2

`service apache2 restart`

and after that the server time is displayed correctly

![image](https://user-images.githubusercontent.com/5565506/233448505-5ea859dd-e84e-4db1-ab03-5fbf1e0e6b3e.png)

I don't know how to implement that in the Dockerfile or entrypoints.sh in fact i don't know in what file it could be implemented xD

**Comment by uebmaster** [comment]
@colisee surely i have a php.ini in the standalone server.

Thanks, anyway i'll try to make the change, although for some reason when i try to build the container and run it i can't see the librebooking site :/

**Comment by uebmaster** [comment]
@colisee  the docker compose needs a php.ini volume pointing to /usr/local/etc/php/php.ini


![image](https://user-images.githubusercontent.com/5565506/233516478-9f2cd5bd-c7ba-4e5e-9cf7-2926e475cd91.png)

and here the content of php.ini

[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone=${TZ}


after that the Mexico's timezone is displayed correctly in Server Settings.

Thanks for the container.

**Comment by colisee** [comment]
@uebmaster , thank you for proposing your solution and submitting a pull request.

I prefer to use a simpler solution that avoids installing a new php extension: modify `entrypoint.sh` in order to create file `/usr/local/etc/php/conf.d/librebooking.ini` with the proper `date.timezone` assignment.

In addition to this change, which solves the issue, I also followed the recommendation of the authors of the `php:7-apache` image by renaming the file `/usr/local/etc/php/php.ini-production` into `/usr/local/etc/php/php.ini` in the `Dockerfile`.

At this stage, I didn't merge the above 2 changes to the `main` branch, yet. Could you kindly build the image by following the [revised instructions](https://github.com/LibreBooking/docker/blob/develop/BUILD.md#option-1) and report whether the solution worked for you?

Saludos.

**Comment by uebmaster** [comment]
@colisee it works, i already see the right timezone in server settings section, but the time still be wrong, it shows one more hour than real time, see screenshot:

![image](https://user-images.githubusercontent.com/5565506/233662651-c3dc4559-78bc-4371-a3d7-8b86bdca5e1c.png)

I think the creation of php.ini its elegant, but the update of timezonedb at least (i think) version 2022.7 (2023.3 last version, i think is better last version) is necessary for people like me, tha live in Mexico, because starting this year there will be no daylight saving time, es posible that you implement that update?

**Comment by colisee** [comment]
@uebmaster , OK got it!

I understand that the problem now is that the timezonedb shipped with the base docker image (php:7-apache) is too old. What you need, is the latest version of timezonedb (olson 2023.3) to take into account the new daylight saving time rules implemented in Mexico.

I now better understand the changes you were proposing in Dockerfile. Nevertheless, I believe that `pecl` should be called from `entrypoint.sh`. 

While I work on the change, you can run the following commands in the `librebooking` container:
```
pecl install timezonedb
echo "extension=timezonedb.so" >> /usr/local/etc/php/conf.d/librebooking.ini
```

**Comment by uebmaster** [comment]
@colisee thanks, one more question, how can i update from version 2.8.5 to version 2.8.6 using docker? Assuming that a new docker container has been released.

Thanks.

**Comment by colisee** [comment]
@uebmaster , I need to review the `Dockerfile` for version 2.8.6, because some php modules must apparently be installed with `composer` now.

Thus you need to be a little patient ;-)

**Comment by colisee** [comment]
@uebmaster , I just pushed the modified `entrypoint.sh` in the `develop` branch. I think this should finally solve/close this issue.

Could you please build the image and test?

**Comment by uebmaster** [comment]
@colisee It Works!!!

**Comment by uebmaster** [comment]
there is something weird :s 

if i change the timezone to the schedule, the timetable looks weird, i need to back the timezone to new york, look at:

This is with schedule's new york timezone
![image](https://user-images.githubusercontent.com/5565506/233754012-89f60cf1-537d-4e98-b3c4-943a75640030.png)

![image](https://user-images.githubusercontent.com/5565506/233753976-3763d99e-2c78-4bb6-9f82-d3520dc75c67.png)


And this is withs chedule's Mexico city timezone
![image](https://user-images.githubusercontent.com/5565506/233754059-0531e196-0123-4526-8cb2-70a6589afde3.png)

![image](https://user-images.githubusercontent.com/5565506/233754087-e70729eb-3d90-483d-bf1c-e7d66dbb5225.png)

If i return to new york's timezone the timetable looks right again.

The server setting's timezone has the correct date and hour accord to Mexico city.

I thinked that could be the update of the timezonedb but I've commented the new lines and it's the same apparently.

Do you think there is no problem if i use the server with mexico's timezone and schedule with new York's timezone?

Thanks in advance.

**Comment by uebmaster** [comment]
there is something weird :s 

if i change the timezone to the schedule, the timetable looks weird, i need to back the timezone to new york, look at:

This is with schedule's new york timezone
![image](https://user-images.githubusercontent.com/5565506/233754012-89f60cf1-537d-4e98-b3c4-943a75640030.png)

![image](https://user-images.githubusercontent.com/5565506/233753976-3763d99e-2c78-4bb6-9f82-d3520dc75c67.png)


And this is withs chedule's Mexico city timezone
![image](https://user-images.githubusercontent.com/5565506/233754059-0531e196-0123-4526-8cb2-70a6589afde3.png)

![image](https://user-images.githubusercontent.com/5565506/233754087-e70729eb-3d90-483d-bf1c-e7d66dbb5225.png)

If i return to new york city timezone the timetable looks right again.

The server setting's timezone has the correct date and hour accord to Mexico city.

I thinked that could be the update of the timezonedb but I've commented the new lines and it's the same apparently.

Do you think there is no problem if i use the server with mexico's timezone and schedule with new York's timezone?

Thanks in advance.

**Comment by colisee** [comment]
@uebmaster,  do you get the same result when you start from a fresh copy; that is:

```
docker-compose down --volumes  # this will delete your 2 librebooking data volumes
docker-compose up -d
# repeat the librebooking setup
```

On my side, the only "weird" sign I saw was that the initial timezone of the `Default` schedule was **"America/New_York"**. 

I changed it to "America/Mexico_City", changed the reservation blocks (from 09:00 to 18:00) and saved it. Then I created the resource. Finally, when displaying the Schedule/Bookings, I could see the proper slots (from 09:00 to 18:00 with 4 slots per hour).

If you cannot delete the docker volumes (because you are in production), then you can try to create a new schedule, making sure it is correct before validating. Then link the resource to the new schedule.

**Comment by uebmaster** [comment]
Maybe my problem is that I'm making the new install importing demo data, I'll check on Monday with a fresh install without demo data.Thanks, have a nice weekend.El 22 abr. 2023 3:45 a. m., Robin ALEXANDER ***@***.***> escribió:
@uebmaster,  do you get the same result when you start from a fresh copy; that is:
docker-compose down --volumes  # this will delete your 2 librebooking data volumes
docker-compose up -d
# repeat the librebooking setup

On my side, the only "weird" sign I saw was that the initial timezone of the Default schedule was "America/New_York".
I changed it to "America/Mexico_City", changed the reservation blocks (from 09:00 to 18:00) and saved it. Then I created the resource. Finally, when displaying the Schedule/Bookings, I could see the proper slots (from 09:00 to 18:00 with 4 slots per hour).
If you cannot delete the docker volumes (because you are in production), then you can try to create a new schedule, making sure it is correct before validating. Then link the resource to the new schedule.

**Comment by uebmaster** [comment]
@colisee i was sure that I've commented that making a fresh install librebooking works fine with the Mexico city timezone :/

Anyway, it works, thanks a lot.
