### ISSUE TITLE
Package sendmail

### ISSUE THREAD

**Issue by ben13300** [LibreBooking/docker#13]
Hello @colisee,
Sorry, I have a new question.
Maybe not a problem, probably misunderstanding.

Did you install the sendmail package in docker image ? Because I have this error in librebooking docker log.

sh:1: /usr/sbin/sendmail: not found
sh:1: /usr/sbin/sendmail: not found

and the mails do not work... I also have a doubt about the smtp.secure parameter between tls and starttls . But the logs rather indicate that the package is not present in the docker.

Thanks

**Comment by ben13300** [comment]
Logs obtenus lorsque je clique sur envoyer une annonce par email

"GET /Web/admin/manage_announcements.php?dr=emailCount&aid=1&_=1681981416409 HTTP/1.1" 200 343 "http://51.83.98.165:6080/Web/admin/manage_announcements.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
sh: 1: /usr/sbin/sendmail: not found
sh: 1: /usr/sbin/sendmail: not found
sh: 1: /usr/sbin/sendmail: not found
sh: 1: /usr/sbin/sendmail: not found

**Comment by colisee** [comment]
Bonjour @ben13300 ,

You are totally right: /usr/sbin/sendmail is missing from the image. From my preliminary tests, I believe I should add the debian package exim4.

Before I make any changes, could you please run the following test on your container:
```
docker exec -tty librebooking sh -c 'DEBIAN_FRONTEND=noninteractive apt-get update; apt-get install -y exim4'
```

Merci pour ton retour.

**Comment by ben13300** [comment]
Dear @colisee , 
No more default in Logs, but no mail sended.
Email server configuration tested with success with thunderbird 
![image](https://user-images.githubusercontent.com/43414622/233407491-f3e80efd-f100-4fcd-b8b1-82464c7b513a.png)

But no succes with phpmail
![image](https://user-images.githubusercontent.com/43414622/233407849-c1fd9780-3743-48f1-9178-5ea34dc19323.png)

Logs :
81.250.224.87 - - [20/Apr/2023:16:51:01 +0200] "-" 408 0 "-" "-"
81.250.224.87 - - [20/Apr/2023:17:05:38 +0200] "GET /Web/admin/manage_announcements.php HTTP/1.1" 200 6201 "http://51.83.98.165:6080/Web/admin/manage_configuration.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
81.250.224.87 - - [20/Apr/2023:17:05:41 +0200] "GET /Web/admin/manage_announcements.php?dr=emailCount&aid=1&_=1682003138549 HTTP/1.1" 200 343 "http://51.83.98.165:6080/Web/admin/manage_announcements.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
81.250.224.87 - - [20/Apr/2023:17:05:43 +0200] "POST /Web/admin/manage_announcements.php?aid=1&action=emailAnnouncement HTTP/1.1" 200 338 "http://51.83.98.165:6080/Web/admin/manage_announcements.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"

**Comment by ben13300** [comment]
Dear @colisee , it's ok for me now, i change mailer field from mail to smtp.

"$conf['settings']['phpmailer']['mailer']

PHP email library. Options are mail, smtp, sendmail, qmail. Default is mail (inherit PHP mail settings)"

Thanks
Thanls

**Comment by colisee** [comment]
Cher @ben13300 ,

In the end, there is no need to add package `exim4` to the container, if one uses the `smtp` mailer.

Thank you for finding out the correct mailer value.

Salutations.

**Comment by ben13300** [comment]
Thank you for your help !!
Best Regards.
