### ISSUE TITLE
Unknown error when trying the docker image

### ISSUE THREAD

**Issue by alaouiz** [LibreBooking/docker#19]
Hello,

 Thanks for this great project.

I'm getting the following error:

![image](https://user-images.githubusercontent.com/28836700/236356010-88c63163-258b-46b2-8511-a191e1c01151.png)

The docker-compose yml I'm using is as follows:

version: "3.7"

services:
  db:
    image: linuxserver/mariadb
    container_name: librebooking-db
    restart: always
    networks:
      - net
    volumes:
      - vol-db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - MYSQL_DATABASE=librebooking
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=lb_user
      - MYSQL_PASSWORD=lb_user
  app:
    image: librebooking/librebooking
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8080:80"
    volumes:
      - vol-app:/var/www/html
    environment: 
      - TZ=America/Toronto
      - LB_DB_HOST=db
      - LB_DB_NAME=librebooking
      - LB_INSTALL_PWD=install
      - LB_DB_USER=lb_user
      - LB_DB_USER_PWD=lb_user

volumes:
  vol-db:
    name: librebooking-db_data
  vol-app:
    name: librebooking_html

networks:
  net:
    name: librebooking

**Comment by alaouiz** [comment]
The following exception is seen from the librebooking docker logs:

PS C:\Users\zalaoui\librebooking> docker logs librebooking   
+ file_env LB_INSTALL_PWD
+ local var=LB_INSTALL_PWD
+ local fileVar=LB_INSTALL_PWD_FILE
+ local def=
++ env
++ grep -E '^LB_INSTALL_PWD='
++ sed -E -e 's/^LB_INSTALL_PWD=//'
+ local varValue=lapnd
++ env
++ grep -E '^LB_INSTALL_PWD_FILE='
++ sed -E -e 's/^LB_INSTALL_PWD_FILE=//'
+ local fileVarValue=
+ '[' -n lapnd ']'
+ '[' -n '' ']'
+ '[' -n lapnd ']'
+ export LB_INSTALL_PWD=lapnd
+ LB_INSTALL_PWD=lapnd
+ unset LB_INSTALL_PWD_FILE
+ file_env LB_DB_USER_PWD
+ local var=LB_DB_USER_PWD
+ local fileVar=LB_DB_USER_PWD_FILE
+ local def=
++ env
++ grep -E '^LB_DB_USER_PWD='
++ sed -E -e 's/^LB_DB_USER_PWD=//'
+ local varValue=lapnd
++ env
++ grep -E '^LB_DB_USER_PWD_FILE='
++ sed -E -e 's/^LB_DB_USER_PWD_FILE=//'
+ local fileVarValue=
+ '[' -n lapnd ']'
+ '[' -n '' ']'
+ '[' -n lapnd ']'
+ export LB_DB_USER_PWD=lapnd
+ LB_DB_USER_PWD=lapnd
+ unset LB_DB_USER_PWD_FILE
+ test -d /var/www/html/config
+ test -d /var/log/librebooking
+ mkdir /var/log/librebooking
+ chown www-data:www-data /var/log/librebooking
+ test -f /var/www/html/composer-setup.php
+ pushd /var/www/html
+ php -r 'copy('\''https://getcomposer.org/installer'\'', '\''composer-setup.php'\'');'
/var/www/html /var/www/html
+ php -r 'if (hash_file('\''sha384'\'', '\''composer-setup.php'\'') === '\''55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae'\'') { echo '\''Installer verified'\''; } else { echo '\''Installer corrupt'\''; unlink('\''composer-setup.php'\''); } echo PHP_EOL;'      
Installer verified
+ php composer-setup.php
All settings correct for using Composer
Downloading...

Composer (version 2.5.5) successfully installed to: /var/www/html/composer.phar
Use it: php composer.phar

+ php -r 'unlink('\''composer-setup.php'\'');'
+ php composer.phar install --ignore-platform-req=ext-gd
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
+ chown -R www-data:www-data /var/www/html
+ popd
+ exec apache2-foreground
/var/www/html
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Fri May 05 02:40:11.821474 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.56 (Debian) PHP/8.1.18 configured -- resuming normal operations
[Fri May 05 02:40:11.821528 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'  
172.18.0.1 - - [05/May/2023:02:40:47 +0200] "GET / HTTP/1.1" 200 250 "-" "Mozilla/5.0 (Windows NT 10.0; 
Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 02:40:47.553405 2023] [php:warn] [pid 61] [client 172.18.0.1:36454] PHP Warning:  Undefined 
array key 1 in /var/www/html/Pages/LoginPage.php on line 117, referer: http://localhost:8080/
[Fri May 05 02:40:47.556553 2023] [php:notice] [pid 61] [client 172.18.0.1:36454] Error: Exception: There was an error executing your query\\nTable 'librebooking.announcements' doesn't exist in /var/www/html/lib/Database/MySQL/MySqlConnection.php:114\nStack trace:\n#0 /var/www/html/lib/Database/MySQL/MySqlConnection.php(76): MySqlConnection->_handleError()\n#1 /var/www/html/lib/Database/Database.php(27): MySqlConnection->Query()\n#2 /var/www/html/Domain/Access/AnnouncementRepository.php(11): Database->Query()\n#3 /var/www/html/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()\n#4 /var/www/html/Pages/LoginPage.php(124): LoginPresenter->PageLoad()\n#5 /var/www/html/Web/index.php(22): LoginPage->PageLoad()\n#6 {main}, referer: http://localhost:8080/
[Fri May 05 02:40:47.556593 2023] [php:notice] [pid 61] [client 172.18.0.1:36454] #0 /var/www/html/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(Exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(Exception))\n, referer: http://localhost:8080/
172.18.0.1 - - [05/May/2023:02:40:47 +0200] "GET /Web/? HTTP/1.1" 200 1969 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 02:40:54.166907 2023] [php:warn] [pid 62] [client 172.18.0.1:36460] PHP Warning:  Undefined 
array key "HTTPS" in /var/www/html/lib/Server/Server.php on line 254
172.18.0.1 - - [05/May/2023:02:40:54 +0200] "GET /Web/install/ HTTP/1.1" 200 2297 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 02:41:18.538939 2023] [php:warn] [pid 63] [client 172.18.0.1:36466] PHP Warning:  Undefined 
array key "HTTPS" in /var/www/html/lib/Server/Server.php on line 254, referer: http://localhost:8080/Web/install/
172.18.0.1 - - [05/May/2023:02:41:18 +0200] "POST /Web/install/index.php HTTP/1.1" 200 2330 "http://localhost:8080/Web/install/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 02:41:23.039206 2023] [php:warn] [pid 63] [client 172.18.0.1:36466] PHP Warning:  Undefined 
array key "HTTPS" in /var/www/html/lib/Server/Server.php on line 254, referer: http://localhost:8080/Web/install/index.php
172.18.0.1 - - [05/May/2023:02:41:22 +0200] "POST /Web/install/index.php HTTP/1.1" 200 2298 "http://localhost:8080/Web/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 02:41:28.062326 2023] [php:warn] [pid 63] [client 172.18.0.1:36466] PHP Warning:  Undefined 
array key "HTTPS" in /var/www/html/lib/Server/Server.php on line 254, referer: http://localhost:8080/Web/install/index.php
172.18.0.1 - - [05/May/2023:02:41:28 +0200] "POST /Web/install/index.php HTTP/1.1" 200 2298 "http://localhost:8080/Web/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:02:41:29 +0200] "GET /Web/dashboard.php HTTP/1.1" 302 397 "http://localhost:8080/Web/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 02:41:29.256448 2023] [php:warn] [pid 63] [client 172.18.0.1:36466] PHP Warning:  Undefined 
array key 1 in /var/www/html/Pages/LoginPage.php on line 117, referer: http://localhost:8080/Web/install/index.php
[Fri May 05 02:41:29.258534 2023] [php:notice] [pid 63] [client 172.18.0.1:36466] Error: Exception: There was an error executing your query\\nTable 'librebooking.announcements' doesn't exist in /var/www/html/lib/Database/MySQL/MySqlConnection.php:114\nStack trace:\n#0 /var/www/html/lib/Database/MySQL/MySqlConnection.php(76): MySqlConnection->_handleError()\n#1 /var/www/html/lib/Database/Database.php(27): MySqlConnection->Query()\n#2 /var/www/html/Domain/Access/AnnouncementRepository.php(11): Database->Query()\n#3 /var/www/html/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()\n#4 /var/www/html/Pages/LoginPage.php(124): LoginPresenter->PageLoad()\n#5 /var/www/html/Web/index.php(22): LoginPage->PageLoad()\n#6 {main}, referer: http://localhost:8080/Web/install/index.php
[Fri May 05 02:41:29.258572 2023] [php:notice] [pid 63] [client 172.18.0.1:36466] #0 /var/www/html/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(Exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(Exception))\n, referer: http://localhost:8080/Web/install/index.php
172.18.0.1 - - [05/May/2023:02:41:29 +0200] "GET /Web/index.php?redirect=%2FWeb%2Fdashboard.php%3F HTTP/1.1" 200 1989 "http://localhost:8080/Web/install/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET / HTTP/1.1" 200 250 "-" "Mozilla/5.0 (Windows NT 10.0; 
Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web? HTTP/1.1" 301 575 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 03:04:15.116342 2023] [php:warn] [pid 64] [client 172.18.0.1:36478] PHP Warning:  Undefined 
array key 1 in /var/www/html/Pages/LoginPage.php on line 117, referer: http://localhost:8080/
[Fri May 05 03:04:15.119341 2023] [php:notice] [pid 64] [client 172.18.0.1:36478] Error: Exception: There was an error executing your query\\nTable 'librebooking.announcements' doesn't exist in /var/www/html/lib/Database/MySQL/MySqlConnection.php:114\nStack trace:\n#0 /var/www/html/lib/Database/MySQL/MySqlConnection.php(76): MySqlConnection->_handleError()\n#1 /var/www/html/lib/Database/Database.php(27): MySqlConnection->Query()\n#2 /var/www/html/Domain/Access/AnnouncementRepository.php(11): Database->Query()\n#3 /var/www/html/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()\n#4 /var/www/html/Pages/LoginPage.php(124): LoginPresenter->PageLoad()\n#5 /var/www/html/Web/index.php(22): LoginPage->PageLoad()\n#6 {main}, referer: http://localhost:8080/
[Fri May 05 03:04:15.119382 2023] [php:notice] [pid 64] [client 172.18.0.1:36478] #0 /var/www/html/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(Exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(Exception))\n, referer: http://localhost:8080/
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web/? HTTP/1.1" 200 2019 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web/scripts/js/jquery-ui-timepicker-addon.js?v=2.8.6 HTTP/1.1" 200 18799 "http://localhost:8080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web/scripts/css/jquery-ui-timepicker-addon.css?v=2.8.6 HTTP/1.1" 200 785 "http://localhost:8080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web/css/null-style.css?v=2.8.6 HTTP/1.1" 200 426 "http://localhost:8080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web/css/booked.css?v=2.8.6 HTTP/1.1" 200 11676 "http://localhost:8080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web/img/librebooking.png?2.8.6 HTTP/1.1" 200 8662 "http://localhost:8080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web/scripts/phpscheduleit.js?v=2.8.6 HTTP/1.1" 200 1890 "http://localhost:8080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:15 +0200] "GET /Web/favicon.ico HTTP/1.1" 200 15388 "http://localhost:8080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 03:04:23.020563 2023] [php:warn] [pid 62] [client 172.18.0.1:36496] PHP Warning:  Undefined 
array key 1 in /var/www/html/Pages/LoginPage.php on line 117, referer: http://localhost:8080/Web/?      
[Fri May 05 03:04:23.022983 2023] [php:notice] [pid 62] [client 172.18.0.1:36496] Error: Exception: There was an error executing your query\\nTable 'librebooking.announcements' doesn't exist in /var/www/html/lib/Database/MySQL/MySqlConnection.php:114\nStack trace:\n#0 /var/www/html/lib/Database/MySQL/MySqlConnection.php(76): MySqlConnection->_handleError()\n#1 /var/www/html/lib/Database/Database.php(27): MySqlConnection->Query()\n#2 /var/www/html/Domain/Access/AnnouncementRepository.php(11): Database->Query()\n#3 /var/www/html/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()\n#4 /var/www/html/Pages/LoginPage.php(124): LoginPresenter->PageLoad()\n#5 /var/www/html/Web/index.php(22): LoginPage->PageLoad()\n#6 {main}, referer: http://localhost:8080/Web/?
[Fri May 05 03:04:23.023018 2023] [php:notice] [pid 62] [client 172.18.0.1:36496] #0 /var/www/html/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(Exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(Exception))\n, referer: http://localhost:8080/Web/?    
172.18.0.1 - - [05/May/2023:03:04:22 +0200] "GET /Web/index.php HTTP/1.1" 200 1969 "http://localhost:8080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
172.18.0.1 - - [05/May/2023:03:04:32 +0200] "GET /Web/dashboard.php HTTP/1.1" 302 398 "http://localhost:8080/Web/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[Fri May 05 03:04:32.550409 2023] [php:warn] [pid 63] [client 172.18.0.1:36502] PHP Warning:  Undefined 
array key 1 in /var/www/html/Pages/LoginPage.php on line 117, referer: http://localhost:8080/Web/index.php
[Fri May 05 03:04:32.552933 2023] [php:notice] [pid 63] [client 172.18.0.1:36502] Error: Exception: There was an error executing your query\\nTable 'librebooking.announcements' doesn't exist in /var/www/html/lib/Database/MySQL/MySqlConnection.php:114\nStack trace:\n#0 /var/www/html/lib/Database/MySQL/MySqlConnection.php(76): MySqlConnection->_handleError()\n#1 /var/www/html/lib/Database/Database.php(27): MySqlConnection->Query()\n#2 /var/www/html/Domain/Access/AnnouncementRepository.php(11): Database->Query()\n#3 /var/www/html/Presenters/LoginPresenter.php(123): AnnouncementRepository->GetFuture()\n#4 /var/www/html/Pages/LoginPage.php(124): LoginPresenter->PageLoad()\n#5 /var/www/html/Web/index.php(22): LoginPage->PageLoad()\n#6 {main}, referer: http://localhost:8080/Web/index.php
[Fri May 05 03:04:32.552973 2023] [php:notice] [pid 63] [client 172.18.0.1:36502] #0 /var/www/html/lib/Common/Logging/ExceptionHandler.php(22): WebExceptionHandler->HandleException(Object(Exception))\n#1 [internal function]: ExceptionHandler::Handle(Object(Exception))\n, referer: http://localhost:8080/Web/index.php
172.18.0.1 - - [05/May/2023:03:04:32 +0200] "GET /Web/index.php?redirect=%2FWeb%2Fdashboard.php%3F HTTP/1.1" 200 1989 "http://localhost:8080/Web/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"

**Comment by colisee** [comment]
Hi @alaouiz,

Thank you for following this project.

Could you please perform the following steps:
1. Delete the containers and volumes
```
sudo docker-compose down --volumes
```
2. Recreate the containers and volumes
```
sudo docker-compose up --detach
```
3. Initialize the application by going to the following url: `http://<YOUR_HOST>:8080/Web/install`
4. Use the application by going to the following url: `http://<YOUR_HOST>:8080/Web/`

**Comment by alaouiz** [comment]
Thanks. This indeed helped. 

Now I'm having the following error during the installation when creating db and the user:
![image](https://user-images.githubusercontent.com/28836700/236456569-3d05ff62-7d98-41e8-9081-a3c21e705050.png)

What are the admin account credentials ? 

Regards

**Comment by colisee** [comment]
Hello again @alaouiz 

My answers:
- the database admin username is `root`
- the database admin password is the value you assigned to environment variable `MYSQL_ROOT_PASSWORD` in file **docker-compose.yml** (ie. *password* as per what you shared with me)

**Comment by colisee** [comment]
@alaouiz , glad I could help you!

As a favor, could you please give me your feed-back on the [project documentation](https://github.com/LibreBooking/docker/blob/main/README.md) ?

In particular:
- Could you find all the info you needed?
- Is the documentation well organized?
- Other suggestions?

Thanks.

**Comment by alaouiz** [comment]
Thanks !

Regarding the questions:
Could you find all the info you needed?
Yes, the installation documentation is quite clear.
2. Is the documentation well organized?
It's well organised and structured in a reasonable way.
Other suggestions?
I would suggest to create a tutorial video.

**Comment by colisee** [comment]
Thank you for your comments and for the idea of a video tutorial.
Are you familiar with the making of such tutorials? If yes, could you help me, for I didn't make any so far.
