### ISSUE TITLE
the Mexico timezone error occurs again in v2.8.6

### ISSUE THREAD

**Issue by uebmaster** [LibreBooking/docker#22]
I wanted to test the upgrade process, so I did a fresh install of v2.8.5, checked the time zone and it was fine, added a resource, user and reservation to test that they persisted when upgrading.

the update process ran without issue,
but when reviewing the server settings I saw that the time had changed to UTC +00:00, when before updating it was fine (America/Mexico_City).

I guess it must be the same as the previous time, the php.ini, because in the application configuration the time zone is set to America/Mexico_City

I hope you can make the correction soon,
while I work with 2.8.5

Greetings.

![image](https://github.com/LibreBooking/docker/assets/5565506/18d0e374-c7d2-46f9-bdc0-4320442bcf61)

![image](https://github.com/LibreBooking/docker/assets/5565506/7fc6ada2-38e2-43e3-90fa-ca2d5c94c011)

**Comment by colisee** [comment]
Hola @uebmaster ,

Well done! Actually, the problem occurs even without upgrading. If you perform:
```
sudo docker-compose down
sudo docker-compose up --detach
```
then the server will revert to UTC.

I spotted the error in `entrypoint.sh`and I will keep you posted.

Saludos.

**Comment by uebmaster** [comment]
@colisee 

` pushd librebooking-docker
-bash: pushd: librebooking-docker: No such file or directory`

**Comment by uebmaster** [comment]
@colisee It works!

although I think that I messed up the installation that I had previously, because by copying and pasting I put the name of the volume that I had in the other installation and not the one of the installation with which I was testing :/

**Comment by colisee** [comment]
Thank you @uebmaster 

I pushed the fix into production and the new docker image to the docker registry.
