### ISSUE TITLE
PHP errors uploading images.

### ISSUE THREAD

**Issue by LensHunnel** [LibreBooking/docker#54]
Hello,

I'm using the following docker's image : librebooking/librebooking:2.8.6-2.1.1

When I try to upload an image file, I get the following error : 

gd extension is required for image upload

How can I fix that issue ? Thanks

**Comment by colisee** [comment]
Hi @LensHunnel 

How do you get this error?
Could you also share the container log?

Cheers.

**Comment by LensHunnel** [comment]
I get this error when I try to upload an image on a ressource and there's nothing significant on logs but it seems like the PHP gd library is not installed. 

![image](https://github.com/LibreBooking/docker/assets/6883486/394ac2db-a152-46f6-bea3-21744fa1d62c)


root@b15e038a0a65:/var/www/html# tail -f /var/log/librebooking/log/app.log

[2023-08-20T16:57:47.154962+02:00] app.INFO: [User=] Action passed all validations [File=/var/www/html/Pages/ActionPage.php,Line=80] [] []
[2023-08-20T16:57:47.155958+02:00] app.INFO: [User=] Processing page action. Action image [File=/var/www/html/Presenters/ActionPresenter.php,Line=67] [] []
[2023-08-20T16:57:47.156012+02:00] app.INFO: [User=] Changing resource image for resource id 5 [File=/var/www/html/Presenters/Admin/ManageResourcesPresenter.php,Line=374] [] []
 #docker compose logs -f
librebooking     | 172.18.0.3 - - [20/Aug/2023:16:56:36 +0200] "POST /Web/admin/manage_resources.php?action=image&rid=2 HTTP/1.1" 200 324 "/Web/admin/manage_resources.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

**Comment by colisee** [comment]
OK, I believe I didn’t include the gd php extension into the docker image.
I will make the change and revert to you.

—-
Colisee

Le 20 août 2023 à 17:06, Lens Hunnel ***@***.***> a écrit :

﻿

I get this error when I try to upload an image on a ressource and there's nothing significant on logs but it seems like the PHP gd library is not installed.

[image]<https://user-images.githubusercontent.com/6883486/261859984-394ac2db-a152-46f6-bea3-21744fa1d62c.png>

***@***.***:/var/www/html# tail -f /var/log/librebooking/log/app.log

[2023-08-20T16:57:47.154962+02:00] app.INFO: [User=] Action passed all validations [File=/var/www/html/Pages/ActionPage.php,Line=80] [] []
[2023-08-20T16:57:47.155958+02:00] app.INFO: [User=] Processing page action. Action image [File=/var/www/html/Presenters/ActionPresenter.php,Line=67] [] []
[2023-08-20T16:57:47.156012+02:00] app.INFO: [User=] Changing resource image for resource id 5 [File=/var/www/html/Presenters/Admin/ManageResourcesPresenter.php,Line=374] [] []
#docker compose logs -f
librebooking | 172.18.0.3 - - [20/Aug/2023:16:56:36 +0200] "POST /Web/admin/manage_resources.php?action=image&rid=2 HTTP/1.1" 200 324 "/Web/admin/manage_resources.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

**Comment by colisee** [comment]
Hi @LensHunnel,

Could you please test the following:
1. Start the librebooking container as you did previously
2. From your host (ie. the hardware where docker is running), run the following commands, assuming that the librebooking container name is librebooking, to install the required gd module:
   ```
   docker exec -it librebooking bash -c 'apt update'
   docker exec -it librebooking bash -c 'apt install -y libpng-dev libjpeg-dev'
   docker exec -it librebooking bash -c 'docker-php-ext-configure gd --with-jpeg'
   docker exec -it librebooking bash -c 'docker-php-ext-install gd'
   ```
3. Try to upload the image

If the test is successful, then I will make the change in the dockerfile.

**Comment by LensHunnel** [comment]
Hi @colisee ,

**Comment by colisee** [comment]
Hi @LensHunnel ,

New docker images are available:
- stable:
  - librebooking/librebooking:2.8.6-2.2.0 (or librebooking/librebooking:2.8.6)
  - librebooking/librebooking:2.8.5.5-2.2.0 (or librebooking/librebooking:2.8.5.5)
- unstable:
  - librebooking/librebooking:develop-2.2.0 (or librebooking/librebooking:develop)
