### ISSUE TITLE
Envio de Mails

### ISSUE THREAD

**Issue by nicolascamanoo** [LibreBooking/docker#73]
Buenas tardes, estoy teniendo problemas con el envió de mails, por ejemplo al momento de recuperar la password.  
no se si me faltara instalar algún paquete en el servidor  o modificar alguna configuracion. Muchas gracias!!!

**Comment by colisee** [comment]
Hola @nicolascamanoo,

could you please share with me your file `docker-compose.yml` ? Do not forget to XXXX any password that might be inside it

Saludos.

**Comment by colisee** [comment]
Regardless of your file `docker-compose.yml` the docker image `librebooking/librebooking` does not include the command `/usr/sbin/sendmail`. This is the reason why you are having this issue.

Could you please apply the following commands:
```
sudo docker exec <librebooking_container_name> sh -c 'apt-get update && apt-get upgrade -y'
sudo docker exec <librebooking_container_name> sh -c 'apt-get install ssmtp -y'
```
This should install the debian package `ssmtp` which contains the command `/usr/sbin/sendmail` inside your container. Once installed, could you please check if the docker image is capable of sending emails?

**Comment by nicolascamanoo** [comment]
no lo tengo levantado en docker, esta directamente en el servidor

**Comment by nicolascamanoo** [comment]
Pude resolverlo, era algo basico de configuracion en la app que no logre ver. Muchas gracias por responder.

**Comment by colisee** [comment]
Hola @nicolascamanoo 

I am glad you solved your issue.

I understand that you are running librebooking on your server without using docker: am I correct?

For my own curiosity, could you please explain (Spanish is fine) how you solved your issue in the applications settings?

Saludos.

**Comment by colisee** [comment]
> Regardless of your file `docker-compose.yml` the docker image `librebooking/librebooking` does not include the command `/usr/sbin/sendmail`. This is the reason why you are having this issue.
> 
> Could you please apply the following commands:
> 
> ```
> sudo docker exec <librebooking_container_name> sh -c 'apt-get update && apt-get upgrade -y'
> sudo docker exec <librebooking_container_name> sh -c 'apt-get install ssmtp -y'
> ```
> 
> This should install the debian package `ssmtp` which contains the command `/usr/sbin/sendmail` inside your container. Once installed, could you please check if the docker image is capable of sending emails?

After a few tests inside a docker container, it looks like there is no need to have /usr/sbin/sendmail when using the `smtp` mode.
