### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by ben13300** [LibreBooking/docker#9]
Hello, 
I am trying to use LibreBooking docker, and i got the classic issue "Unknow error". Which PHP's version did you use inside your docker ?
Thanks.
Benoit (Newbie)

**Comment by colisee** [comment]
Hi @ben13300 ,

the current docker image (2.8.5.5) is based on Apache:php-7 

Normally, you should have no issues… Dis you try one of the docker-compose.yml samples I mentioned inside the README.md document?

Kind regards. 

Robin

**Comment by ben13300** [comment]
I tested it an other time.. Same issue.
Thanks
Benoit

+ test -d /var/www/html/config
+ exec apache2-foreground
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.3. Set the 'ServerName' directive globally to suppress this message
[Tue Apr 18 16:26:10.742959 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/7.4.30 configured -- resuming normal operations
[Tue Apr 18 16:26:10.743029 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET / HTTP/1.1" 200 250 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /Web? HTTP/1.1" 301 587 "http://192.168.1.109:7080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /favicon.ico HTTP/1.1" 404 494 "http://192.168.1.109:7080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /Web/? HTTP/1.1" 200 2037 "http://192.168.1.109:7080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /Web/scripts/css/jquery-ui-timepicker-addon.css?v=2.8.5.5 HTTP/1.1" 200 784 "http://192.168.1.109:7080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /Web/scripts/js/jquery-ui-timepicker-addon.js?v=2.8.5.5 HTTP/1.1" 200 18799 "http://192.168.1.109:7080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /Web/css/null-style.css?v=2.8.5.5 HTTP/1.1" 200 426 "http://192.168.1.109:7080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /Web/css/booked.css?v=2.8.5.5 HTTP/1.1" 200 11676 "http://192.168.1.109:7080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /Web/img/booked.png?2.8.5.5 HTTP/1.1" 304 249 "http://192.168.1.109:7080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:24 +0000] "GET /Web/scripts/phpscheduleit.js?v=2.8.5.5 HTTP/1.1" 200 1890 "http://192.168.1.109:7080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:26:27 +0000] "GET /Web/view-schedule.php HTTP/1.1" 200 1906 "http://192.168.1.109:7080/Web/?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
127.0.0.1 - - [18/Apr/2023:16:26:31 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.54 (Debian) PHP/7.4.30 (internal dummy connection)"
127.0.0.1 - - [18/Apr/2023:16:26:35 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.54 (Debian) PHP/7.4.30 (internal dummy connection)"
172.20.0.1 - - [18/Apr/2023:16:32:44 +0000] "\x16\x03\x01\x02" 400 484 "-" "-"
172.20.0.1 - - [18/Apr/2023:16:32:44 +0000] "\x16\x03\x01\x02" 400 484 "-" "-"
172.20.0.1 - - [18/Apr/2023:16:32:44 +0000] "\x16\x03\x01\x02" 400 484 "-" "-"
172.20.0.1 - - [18/Apr/2023:16:32:44 +0000] "\x16\x03\x01\x02" 400 484 "-" "-"
172.20.0.1 - - [18/Apr/2023:16:32:54 +0000] "GET / HTTP/1.1" 200 250 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:32:54 +0000] "GET /Web/? HTTP/1.1" 200 1981 "http://192.168.1.109:7080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
172.20.0.1 - - [18/Apr/2023:16:33:45 +0000] "-" 408 0 "-" "-"

**Comment by colisee** [comment]
Hi @ben13300,

I could not see anything wrong from the log output you shared with me.

Here are my questions:
1. In the docker-compose.yml file, did you set values for variables **MYSQL_ROOT_PASSWORD**, **MYSQL_PASSWORD**, **TZ**, **LB_INSTALL_PWD** and **LB_DB_USER_PWD**? The examples I gave come without values...
2. If you set values for the above variables, then could you share the screen copies from the moment you run the [application setup](https://github.com/LibreBooking/docker#application-setup) ?

**Comment by ben13300** [comment]
Hi @colisee , 
Thanks for your help.
I setted now values (sorry for my previous mistake) and here a screen copie of the application setup page.
![image](https://user-images.githubusercontent.com/43414622/233058119-6bbaaf8c-1aac-45cc-8d13-1a405b94b4c9.png)

**Comment by colisee** [comment]
Bonjour @ben13300,

The screen copy indicates that you did not set the installation password for librebooking (environment variable **LB_INSTALL_PWD**). But there is also an issue connecting to the mariadb container, apparently...

Could you please share your docker-compose.yml file ?

Merci.

Robin

**Comment by ben13300** [comment]
Here the file, thanls for 4 help. I put the same Password everywhere.

(txt extension puted to allow upload on the site=
[docker-compose.yml.txt](https://github.com/LibreBooking/docker/files/11272905/docker-compose.yml.txt)

**Comment by colisee** [comment]
Benoît,

Please run these commands when performing the new attempt:
```
docker volume rm librebooking_html librebooking-db_data
docker-compose up --detach
```

This will make sure that the 2 volumes are re-created anew.

**Comment by ben13300** [comment]
OK thanks you.
SI first try, without removing the 2 volumes ---> Same issue.
Second try, with removing the 2 volumes --> Good news, but connection mysql refused

Step 1 :
![image](https://user-images.githubusercontent.com/43414622/233134600-2bff162d-b996-4ee0-8b5e-2066e47ed621.png)

Step 2:
![image](https://user-images.githubusercontent.com/43414622/233134878-41d78624-1391-4330-af05-f1ed34423b83.png)

Step 3 :
![image](https://user-images.githubusercontent.com/43414622/233135500-2a639467-b7a8-42cb-b77e-09eec0e0047b.png)
All is correct NOW !!!

THANK YOU VERY MUCH, sorry for my fist mistake (no password).

**Comment by ben13300** [comment]
The first SQL warning should be ignored.
