### ISSUE TITLE
Where is `PHP_INI_DIR` defined?

### ISSUE THREAD

**Issue by JohnVillalovos** [LibreBooking/docker#90]
In https://github.com/LibreBooking/docker/blob/d011ffa62ed83835ae0088ccb586c9f17d025b80/Dockerfile#L26

It uses the variable `PHP_INI_DIR`. I couldn't find that variable defined and was wondering how it is being set.

Thanks!

**Comment by colisee** [comment]
Hi @JohnVillalovos,

The environment variable `PHP_INI_DIR` is defined inside the image `php:*-apache` which is used as a base for `librebooking/docker`

**Comment by JohnVillalovos** [comment]
> Hi @JohnVillalovos,
> 
> The environment variable `PHP_INI_DIR` is defined inside the image `php:*-apache` which is used as a base for `librebooking/docker`

Thanks! Now it makes sense.
